lmax_over_nside = 2.5
healpix = true
car = false
output_folder = "output/{tag}"
output_filename_template= "sobs_mbs-s0020-20250423_{telescope}_mission_{band}_{tag}_{pixelization}.fits"
unit = "uK_CMB"
num = 0
output_reference_frame = "C"
instrument_parameters = "instrument_model/instrument_model.tbl"
