lmax_over_nside = 2.5
healpix = true
car = true
output_folder = "output/{tag}"
output_filename_template= "sobs_mbs-s0012-20230321_{telescope}_mission_{band}_{tag}_{pixelization}.fits"
unit = "uK_CMB"
num = 0
output_reference_frame = "C"
mapsims_version = "2.6.0"
instrument_parameters = "simonsobs_instrument_parameters_2023.03/simonsobs_instrument_parameters_2023.03.tbl"
