lmax_over_nside = 2.5
healpix = true
car = true
output_folder = "output/{tag}"
output_filename_template= "sobs_{tag}_{telescope}_mission_{band}_{tag}_{pixelization}.fits"
unit = "uK_CMB"
num = 0
output_reference_frame = "C"
mapsims_version = "2.5.0"
instrument_parameters = "simonsobs_instrument_parameters_2023.03/simonsobs_instrument_parameters_2023.03.tbl"
output_resolution = "simonsobs_instrument_parameters_2023.03/so_default_resolution.csv"
