output_folder = "output/{tag}/{num:04d}"
output_filename_template="simonsobs_{tag}_uKCMB_{telescope}_{band}_CAR_{num:04d}_{split}_of_{nsplits}.fits"
car = true
channels = "tube:ST3"
unit = "uK_CMB"
mapsims_version = "2.3.2"
so_pysm_models_version = "2.3.2"
num = 0
nsplits = 1
instrument_parameters = "simonsobs_instrument_parameters_2020.06"
