#!/bin/bash
##SBATCH --job-name=run00
##SBATCH --partition=cmbas
##SBATCH --constraint=rome
##SBATCH --nodes=1

##SBATCH --ntasks-per-node=60
##SBATCH --cpus-per-task=2

##SBATCH --time=01:20:00

#export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export OMP_NUM_THREADS=20

module load adri_gcc
module load adri_base

source /mnt/home/aduivenvoorden/.pyenv/versions/enki/bin/activate

TAG=run00
MNMSDIR="/mnt/home/aduivenvoorden/local/mnms/scripts"

CONFIG="so_lat_mbs_mss0002"
LMAX=5400

SIMS_END=1

#for FTYPE in 'lf' 'mf' 'uhf'
for FTYPE in 'uhf'
do
    if [ ${FTYPE} = 'lf' ]
    then
        QIDS="lfa lfb"
	NOISEMODEL="fdw_lf"
    fi
    if [ ${FTYPE} = 'mf' ]
    then
        QIDS="mfa mfb"
	NOISEMODEL="fdw_mf"
    fi
    if [ ${FTYPE} = 'uhf' ]
    then
        QIDS="uhfa uhfb"
	NOISEMODEL="fdw_uhf"
    fi
    
    #srun -u python ${MNMSDIR}/noise_gen.py --config-name ${CONFIG} --noise-model-name ${NOISEMODEL} --qid ${QIDS} --lmax ${LMAX} --use-mpi
    #srun -u python ${MNMSDIR}/noise_sim.py --config-name ${CONFIG} --noise-model-name ${NOISEMODEL} --qid ${QIDS} --lmax ${LMAX} --use-mpi --maps-start 0 --maps-end ${SIMS_END}

    srun -u -n 2 python ${MNMSDIR}/noise_gen.py --config-name ${CONFIG} --noise-model-name ${NOISEMODEL} --qid ${QIDS} --lmax ${LMAX} --use-mpi
    srun -u -n 2 python ${MNMSDIR}/noise_sim.py --config-name ${CONFIG} --noise-model-name ${NOISEMODEL} --qid ${QIDS} --lmax ${LMAX} --use-mpi --maps-start 0 --maps-end ${SIMS_END}

done
