
tag = "cmb_lensed_solardipole"

[ pysm_components ]
# do not apply any rotation
pysm_output_reference_frame = "C"

    [ pysm_components.cmb ]
    class  =  "so_pysm_models.WebSkyCMBMap"
    websky_version = "0.3"
    lensed = true
    include_solar_dipole = true
    seed = 1
