nside = 512
output_folder = "/simons/scratch/zonca/simonsobs/map_based_simulations/201906_noise_no_lowell/{nside}/{tag}/{num:04d}"
output_filename_template="simonsobs_{tag}_uKCMB_{telescope}{band:03d}_nside{nside}_{num:04d}.fits"
channels = "all"
unit = "uK_CMB"
mapsims_version = "1.0.0"
so_pysm_models_version = "1.0.0"
